### ISSUE TITLE
Not all Messages documented

### ISSUE THREAD

**Issue by 312c** [LIFX/lifx-protocol-docs#2]
There are at least 7 messages that are not covered by the current documentation.  Using the latest firmware my lights are broadcasting messages with the following undocumented IDs:
50
53
56
111
The official android app broadcasts messages with the following undocumented IDs:
48
51
54

**Comment by dotMorten** [comment]
Also: Missing doc on how to onboard a light to your wifi network.

For what's it's worth according to https://github.com/magicmonkey/lifxjs/blob/master/Protocol.md, `111` = Temperature State.

**Comment by smarthall** [comment]
This is a first cut of the documentation as as such not everything is implemented in it. We had to strike a balance between documenting everything and getting this document out quickly. This also wont be the last version of the documentation and we will to keep improving it as we get time.

For now though, can I ask that you raise issues for the features you want instead of undocumented messages. This will allow us to focus our efforts getting the features people want.

**Comment by dotMorten** [comment]
Definitely. See #1

**Comment by smarthall** [comment]
Yup, I'm following that one up internally right now. Expect a response shortly. :smile:

**Comment by tmazeika** [comment]
@smarthall Just curious, are there any updates on this documentation? I'm working on an emulator for LIFX bulbs, and it seems that I'm unable to claim the bulb from the Android app (but I can control the color/power/etc.), and I can't be sure if these undocumented messages are necessary to get it working.
